### ISSUE TITLE
Not compatible with PubPeer zotero plugin

### ISSUE THREAD

**Issue by YCChiang** [scitedotai/scite-zotero-plugin#41]
I install both Scite and PubPeer pulgin, but it crashed like image show below.

![WeChat Screenshot_20220404202531](https://user-images.githubusercontent.com/41322112/161543185-99d4a9de-042e-48a6-aa30-c904e2f6ea3d.png)

Zotero Vesion: 6.0.4
Scite plugin version: 1.11.5
PubPeer plugin version: 0.0.13

Error Massage:
![WeChat Screenshot_20220404202717](https://user-images.githubusercontent.com/41322112/161543396-6a4bbade-eced-46e0-a60c-99e0e0a6d80e.png)

**Comment by u-ashish** [comment]
Thanks for reporting this @YCChiang, I can take a look. Just to confirm, is the scite plugin working for you on that version of zotero without PubPeer?

**Comment by YCChiang** [comment]
> Thanks for reporting this @YCChiang, I can take a look. Just to confirm, is the scite plugin working for you on that version of zotero without PubPeer?

Scite pulgin works well without PubPeer, @u-ashish

**Comment by YCChiang** [comment]
> Thanks for reporting this @YCChiang, I can take a look. Just to confirm, is the scite plugin working for you on that version of zotero without PubPeer?

Scite pulgin works well without PubPeer, @u-ashish

**Comment by u-ashish** [comment]
@YCChiang could you try upgrading PubPeer to the latest (0.0.14) and see if that works? Download here -- https://github.com/PubPeerFoundation/pubpeer_zotero_plugin/releases/tag/v0.0.14

When I was trying to reproduce it, I tried with PubPeer 0.0.13 and saw the following error message:

<img width="684" alt="Screen Shot 2022-04-04 at 3 05 57 PM" src="https://user-images.githubusercontent.com/14264791/161623191-a57255b3-6300-43f8-b913-9365c0078485.png">

But then I upgraded PubPeer and everything worked:

<img width="1232" alt="Screen Shot 2022-04-04 at 3 09 49 PM" src="https://user-images.githubusercontent.com/14264791/161623848-f85e791b-4808-4d6a-bf6a-7b52bdb0de26.png">

Let me know if the issue persists for you with PubPeer 0.0.14. My guess is that the bug got fixed in this commit on their end -- https://github.com/PubPeerFoundation/pubpeer_zotero_plugin/commit/e2aa5378159dead3e4bfd630263628097248298b#diff-f0161d1714902ef2c771ff2fedc168aa3dd210409fcec6543ef1196ed06cbb93R98

(ccing @retorquere in case they might have more context)

**Comment by retorquere** [comment]
No need to address me by royal plural 😁. Yes, that's the right commit. Looks like zotero doesn't accept simple strings anymore as cell content.

**Comment by u-ashish** [comment]
@YCChiang I am going to close this since it appears to be working with 0.0.14, but if you find that it doesn't, please feel free to re-open!

**Comment by drchriscole** [comment]
I have both pubpeer 0.0.14 and scite 1.11.6 and still see the error. It works if I disable pubpeer.

**Comment by drchriscole** [comment]
Interestingly, when re-enabling the pubpeer plugin, the scite columnar data is working and will update with new additions to Zotero, however, scite tab is blank.
